import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export const metadata = {
  title: "Restaurant Booking System",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "Arial, sans-serif" }}>
        <nav className="navbar">
          <h1>Restaurant Booking</h1>
        </nav>
        {children}
        <footer className="footer">
          &copy; 2025 Restaurant Booking System
        </footer>
      </body>
    </html>
  );
}

